### ISSUE TITLE
Entire solution does not build on Linux

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/WPILib#99]
System.Reflection.Context does not seem to exist in Mono, which cause the unit test building to fail.

**Comment by jkoritzinsky** [comment]
I'll work on making replacement for CustomReflectionContext (which is the class from that assembly)

**Comment by jkoritzinsky** [comment]
After looking at the code, I can't get access to enough of the internals of the reflection stuff to make a replacement. I can either remove the ReflectionContext code or we can make the tests that test it conditionally compile on Linux.  It'll probably be better to just remove the code since CustomReflectionContext is really the only way to use it.

**Comment by ThadHouse** [comment]
Ah. Yeah if we can't use it on Mono on the robot there's no point in having it.
